name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: install dependencies
        run: yarn install
      - name: tsc
        run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: run tests
        run: yarn test --coverage
      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/**/lcov.info
          name: code-coverage
          fail_ci_if_error: true
